import { useApp } from '../App';
import { motion } from 'framer-motion';
import { Copy, Check, Zap, Smartphone } from 'lucide-react';
import { useState } from 'react';

const fadeIn = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.4 },
};

// Free Fire scope icons as inline SVGs
function ScopeIcon({ type }: { type: string }) {
  const colors: Record<string, string> = {
    general: '#D4AF37',
    redDot: '#EF4444',
    twoX: '#3B82F6',
    fourX: '#8B5CF6',
    sniper: '#10B981',
    freeLook: '#F59E0B',
  };
  const color = colors[type] || '#D4AF37';

  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
      <circle cx="8" cy="8" r="6" stroke={color} strokeWidth="1.5" fill="none" opacity="0.6" />
      <circle cx="8" cy="8" r="2" fill={color} opacity="0.8" />
      <line x1="8" y1="1" x2="8" y2="4" stroke={color} strokeWidth="1" opacity="0.5" />
      <line x1="8" y1="12" x2="8" y2="15" stroke={color} strokeWidth="1" opacity="0.5" />
      <line x1="1" y1="8" x2="4" y2="8" stroke={color} strokeWidth="1" opacity="0.5" />
      <line x1="12" y1="8" x2="15" y2="8" stroke={color} strokeWidth="1" opacity="0.5" />
    </svg>
  );
}

export default function SensiTab() {
  const { device, sensi, generateSensi, sensiGenerated, siteAssets, settings } = useApp();
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (!sensi) return;
    const text = `🎯 ${settings.siteName} - Free Fire Sensi
📱 Device: ${device?.model || 'Unknown'}
━━━━━━━━━━━━━━━━
General: ${sensi.general}
Red Dot: ${sensi.redDot}
2x Scope: ${sensi.twoX}
4x Scope: ${sensi.fourX}
AWM/Sniper: ${sensi.sniper}
Free Look: ${sensi.freeLook}
DPI: ${sensi.dpi}
Button Size: ${sensi.buttonSize}%
━━━━━━━━━━━━━━━━
🔥 Generated by ${settings.siteName}`;

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (!sensiGenerated || !sensi) {
    return (
      <div className="px-4 pt-6 space-y-6">
        <motion.div {...fadeIn}>
          <div className="text-center py-12">
            {/* Crosshair SVG */}
            <div className="w-20 h-20 mx-auto bg-dark-surface rounded-full flex items-center justify-center mb-4 relative">
              <svg width="44" height="44" viewBox="0 0 44 44" fill="none">
                <circle cx="22" cy="22" r="16" stroke="#D4AF37" strokeWidth="1.5" fill="none" opacity="0.3" />
                <circle cx="22" cy="22" r="8" stroke="#D4AF37" strokeWidth="1" fill="none" opacity="0.5" />
                <circle cx="22" cy="22" r="2" fill="#D4AF37" opacity="0.8" />
                <line x1="22" y1="2" x2="22" y2="10" stroke="#D4AF37" strokeWidth="1.5" opacity="0.4" />
                <line x1="22" y1="34" x2="22" y2="42" stroke="#D4AF37" strokeWidth="1.5" opacity="0.4" />
                <line x1="2" y1="22" x2="10" y2="22" stroke="#D4AF37" strokeWidth="1.5" opacity="0.4" />
                <line x1="34" y1="22" x2="42" y2="22" stroke="#D4AF37" strokeWidth="1.5" opacity="0.4" />
              </svg>
            </div>
            <h2 className="text-white font-bold text-lg mb-2">Generate Your Sensi</h2>
            <p className="text-white/50 text-sm mb-6 max-w-xs mx-auto">
              Our algorithm analyzes your device specs and generates optimized Free Fire sensitivity (max 200)
            </p>
            {device && (
              <div className="bg-dark-card border border-white/5 rounded-2xl p-4 mb-6 text-left max-w-xs mx-auto">
                <div className="flex items-center gap-2 mb-3">
                  <Smartphone className="w-4 h-4 text-gold" />
                  <p className="text-white/50 text-[11px] font-semibold">DETECTED DEVICE</p>
                </div>
                <div className="space-y-2">
                  {[
                    { label: 'Brand', value: device.brand },
                    { label: 'Model', value: device.model },
                    { label: 'OS', value: `${device.os} ${device.osVersion}` },
                    { label: 'Battery', value: `${device.battery}%${device.charging ? ' ⚡ Charging' : ''}` },
                    { label: 'Refresh Rate', value: `${device.refreshRate}Hz` },
                    { label: 'Tier', value: device.tier.toUpperCase(), isGold: true },
                  ].map((item) => (
                    <div key={item.label} className="flex justify-between items-center">
                      <span className="text-white/40 text-xs">{item.label}</span>
                      <span className={`text-xs font-medium ${item.isGold ? 'text-gold font-bold' : 'text-white'}`}>
                        {item.value}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}
            <button
              onClick={generateSensi}
              className="bg-gold text-dark font-bold text-sm py-3.5 px-8 rounded-full flex items-center justify-center gap-2 mx-auto active:scale-[0.97] transition-transform"
            >
              <Zap className="w-4 h-4" />
              Generate My Sensi
            </button>
          </div>
        </motion.div>
      </div>
    );
  }

  // MAX IS 200
  const sensiValues = [
    { key: 'general', label: 'General', value: sensi.general, max: 200, color: 'from-gold to-gold-light' },
    { key: 'redDot', label: 'Red Dot', value: sensi.redDot, max: 200, color: 'from-red-500 to-red-400' },
    { key: 'twoX', label: '2x Scope', value: sensi.twoX, max: 190, color: 'from-blue-500 to-blue-400' },
    { key: 'fourX', label: '4x Scope', value: sensi.fourX, max: 170, color: 'from-purple-500 to-purple-400' },
    { key: 'sniper', label: 'AWM / Sniper', value: sensi.sniper, max: 150, color: 'from-emerald-500 to-emerald-400' },
    { key: 'freeLook', label: 'Free Look', value: sensi.freeLook, max: 180, color: 'from-amber-500 to-amber-400' },
  ];

  return (
    <div className="px-4 pt-6 space-y-4">
      {/* Device Info */}
      <motion.div {...fadeIn}>
        <div className="bg-dark-card border border-white/5 rounded-2xl p-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gold/10 rounded-xl flex items-center justify-center">
              <Smartphone className="w-5 h-5 text-gold" />
            </div>
            <div className="flex-1">
              <p className="text-white font-bold text-sm">{device?.model || 'Unknown'}</p>
              <p className="text-white/40 text-[11px]">
                {device?.os} {device?.osVersion} · {device?.refreshRate}Hz · {device?.battery}%{device?.charging ? ' ⚡' : ''}
              </p>
            </div>
            <span className="bg-gold/10 text-gold text-[10px] font-bold px-2 py-1 rounded-lg">
              {device?.tier?.toUpperCase()}
            </span>
          </div>
        </div>
      </motion.div>

      {/* Phone Mockup with FF Sensi overlay */}
      <motion.div {...fadeIn} transition={{ delay: 0.1 }}>
        <div className="relative rounded-2xl overflow-hidden bg-dark-card border border-white/5">
          <div className="relative">
            <img
              src={siteAssets.phoneMockupImage}
              alt="Free Fire Sensitivity Settings"
              className="w-full h-44 object-cover opacity-60"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-dark-card via-dark-card/60 to-transparent" />
            {/* FF-style sensi overlay */}
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="text-center">
                <svg width="48" height="48" viewBox="0 0 48 48" fill="none" className="mx-auto mb-2">
                  <circle cx="24" cy="24" r="18" stroke="#D4AF37" strokeWidth="2" fill="none" opacity="0.4" />
                  <circle cx="24" cy="24" r="10" stroke="#D4AF37" strokeWidth="1.5" fill="none" opacity="0.6" />
                  <circle cx="24" cy="24" r="3" fill="#D4AF37" />
                  <line x1="24" y1="2" x2="24" y2="10" stroke="#D4AF37" strokeWidth="2" opacity="0.5" />
                  <line x1="24" y1="38" x2="24" y2="46" stroke="#D4AF37" strokeWidth="2" opacity="0.5" />
                  <line x1="2" y1="24" x2="10" y2="24" stroke="#D4AF37" strokeWidth="2" opacity="0.5" />
                  <line x1="38" y1="24" x2="46" y2="24" stroke="#D4AF37" strokeWidth="2" opacity="0.5" />
                </svg>
                <p className="text-gold font-display font-black text-sm">OPTIMIZED FOR YOU</p>
                <p className="text-white/40 text-[10px]">Max sensitivity: 200</p>
              </div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Sensi Values - MAX 200 */}
      <motion.div {...fadeIn} transition={{ delay: 0.15 }}>
        <div className="bg-dark-card border border-white/5 rounded-2xl p-4 space-y-3">
          <div className="flex items-center gap-2">
            <h3 className="text-white font-bold text-sm">Sensitivity Settings</h3>
            <span className="text-[9px] bg-green-safe/10 text-green-safe px-1.5 py-0.5 rounded-full">FF Max 200</span>
          </div>
          {sensiValues.map((s, i) => (
            <motion.div
              key={s.label}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2 + i * 0.05 }}
            >
              <div className="flex items-center justify-between mb-1">
                <div className="flex items-center gap-1.5">
                  <ScopeIcon type={s.key} />
                  <span className="text-white/50 text-xs">{s.label}</span>
                </div>
                <span className="text-gold font-bold text-sm">{s.value}</span>
              </div>
              <div className="h-1.5 bg-dark-surface rounded-full overflow-hidden">
                <motion.div
                  className={`h-full bg-gradient-to-r ${s.color} rounded-full`}
                  initial={{ width: 0 }}
                  animate={{ width: `${(s.value / s.max) * 100}%` }}
                  transition={{ delay: 0.3 + i * 0.05, duration: 0.6, ease: 'easeOut' }}
                />
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* DPI & Button Size */}
      <motion.div {...fadeIn} transition={{ delay: 0.3 }}>
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-dark-card border border-white/5 rounded-2xl p-4 text-center">
            <p className="text-white/40 text-[11px] mb-1">DPI</p>
            <p className="text-gold font-black text-2xl">{sensi.dpi}</p>
            <p className="text-white/20 text-[9px] mt-0.5">Dots Per Inch</p>
          </div>
          <div className="bg-dark-card border border-white/5 rounded-2xl p-4 text-center">
            <p className="text-white/40 text-[11px] mb-1">Button Size</p>
            <p className="text-gold font-black text-2xl">{sensi.buttonSize}%</p>
            <p className="text-white/20 text-[9px] mt-0.5">HUD Controls</p>
          </div>
        </div>
      </motion.div>

      {/* Copy Button */}
      <motion.div {...fadeIn} transition={{ delay: 0.35 }} className="pb-6">
        <button
          onClick={handleCopy}
          className={`w-full py-3.5 rounded-full font-bold text-sm flex items-center justify-center gap-2 active:scale-[0.97] transition-all ${
            copied
              ? 'bg-green-safe text-white'
              : 'bg-gold text-dark'
          }`}
        >
          {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          {copied ? '✅ Copied!' : '📋 Copy Settings'}
        </button>
      </motion.div>
    </div>
  );
}
